---
- name: reload systemd
  become: yes
  become_user: root
  command: /bin/systemctl daemon-reload

- name: restart php-resque
  service: name=php-resque enabled=yes state=restarted

- name: restart deploynaut-pipelines
  service: name=deploynaut-pipelines enabled=yes state=restarted

- name: restart apache
  service: name=apache2 enabled=yes state=restarted
